apiVersion: v1
kind: Namespace
metadata:
  name: serviceapp

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
  namespace: serviceapp
  labels:
    app: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
      - name: test
        image: zeromaxinc/argocd:latest
        ports:
        - containerPort: 8888

      
