apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
  namespace: serviceapp
  labels:
    app: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
      - name: test
        image: zeromaxinc/argocd:v1.0.5
        ports:
        - containerPort: 8888
  revisionHistoryLimit: 1
