---
apiVersion: v1
kind: Service
metadata:
  name: test
  namespace: serviceapp
spec:
  selector:
    app: test
  type: ClusterIP
  ports:
    - name: test
      port: 8000
      targetPort: 8000
      protocol: TCP
