name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1


      - name: Determine Next Version
        id: version
        run: |
          # Your versioning logic/script here
          NEXT_VERSION=$(.github/workflows/calculate_version.sh)
          echo "Next version: $NEXT_VERSION"
          echo "NEXT_VERSION=$NEXT_VERSION" >> $GITHUB_ENV  

      - name: Log in to Docker Hub
        if: ${{ success() }}
        env:
          DOCKER_USER: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD


      - name: Build and Push Docker Image
        if: ${{ success() }}
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            -t zeromaxinc/argocd:${NEXT_VERSION} \
            -t zeromaxinc/argocd:latest \
            --push \
            .