name: Deployment workflow
on:
  push:
    branches: [ "main" ]
jobs:
  deployment:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Log in to Docker Hub
        env:
          DOCKER_USER: zeromaxinc
          DOCKER_PASSWORD: zoqhuB-howwyd-3xocty
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      
      - name: Build the Docker image
        run: docker build -t argocd . && docker tag argocd zeromaxinc/argocd:v1.0.2
    
      - name: Docker push
        run: docker push zeromaxinc/argocd:v1.0.2

