name: Deployment workflow

on:
  push:
    branches:
      - main

jobs:
  deployment:
    name: Deploy
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Get latest tag
        id: get_tag
        run: echo "::set-output name=tag::$(git describe --tags --abbrev=0)"
        
      - name: Extract major, minor, and patch versions
        id: extract_versions
        run: |
          IFS='.' read -r major minor patch <<< "${{ steps.get_tag.outputs.tag }}"
          major="${major//v/}"
          echo "::set-output name=major::$major"
          echo "::set-output name=minor::$minor"
          echo "::set-output name=patch::$patch"
      
      - name: Increment patch version
        id: increment_patch
        run: echo "::set-output name=patch::$((${{ steps.extract_versions.outputs.patch }} + 1))"
      
      - name: Set new version
        id: set_new_version
        run: |
          new_version="${{ steps.extract_versions.outputs.major }}.${{ steps.extract_versions.outputs.minor }}.$((${{
          steps.increment_patch.outputs.patch }}))"
          echo "::set-output name=new_version::$new_version"
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      
      - name: Build and push Docker image
        run: |
          docker build -t zeromaxinc/argocd:${{ steps.set_new_version.outputs.new_version }} .
          docker push zeromaxinc/argocd:${{ steps.set_new_version.outputs.new_version }}
