name: Deployment workflow

on:
  push:
    branches: [ "main" ]

jobs:
  deployment:
    name: Deploy
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Log in to Docker Hub
        env:
          DOCKER_USER: zeromaxinc
          DOCKER_PASSWORD: zoqhuB-howwyd-3xocty
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      
      - name: Get latest tag
        id: get_tag
        run: echo "::set-output name=tag::$(git describe --tags --abbrev=0)"
        
      - name: Extract major, minor, and patch versions
        id: extract_versions
        run: |
          IFS='.' read -r major minor patch <<< "${{ steps.get_tag.outputs.tag }}"
          major="${major//v/}"
          echo "::set-output name=major::$major"
          echo "::set-output name=minor::$minor"
          echo "::set-output name=patch::$patch"
      
      - name: Increment patch version
        id: increment_patch
        run: echo "::set-output name=patch::$((${{ steps.extract_versions.outputs.patch }} + 1))"
      
      - name: Set new version
        id: set_new_version
        run: echo "::set-output name=new_version::${{ steps.extract_versions.outputs.major }}.${{ steps.extract_versions.outputs.minor }}.${{ steps.increment_patch.outputs.patch }}"
      
      - name: Log in to Docker Hub
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      
      - name: Build the Docker image
        run: |
          docker build -t argocd .
          docker tag argocd zeromaxinc/argocd:${{ steps.set_new_version.outputs.new_version }}
    
      - name: Docker push
        run: docker push zeromaxinc/argocd:${{ steps.set_new_version.outputs.new_version }}
