

name: Docker Publish

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Determine Version Change
        id: version
        run: echo "::set-output name=version::$(bash determine_version.sh)"

      - name: Build and Push Docker Image
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 -t zeromaxinc/argocd:${{ steps.version.outputs.version }} .
          docker push zeromaxinc/argocd:${{ steps.version.outputs.version }}
